// fundamentos-ordem-livros/ordem-livros/src/components/template/MenuItem.svelte
<script>
  /* We can forget to export in svelte, otherwise it will not know there is a variable inside of here*/
  export let texto = "";
  export let link = "";
</script>

<li>
  <a
    href={link}
    class="flex gap-2 px-4 py-2 items-center cursor-pointer text-zinc-300
    hover:text-white hover:underline hover:bg-white/10"
  >
    <span>{texto}</span>
  </a>
</li>

// mentoria/specialist/Next.Js/fundamentals/fundamentals-1/src/components/template/MenuItem.tsx
import Link from 'next/link'

export interface MenuItemProps {
	url: string
	icon: React.ReactNode
	text: string
	className?: string
}

export const MenuItem = ({
	url,
	icon,
	text,
	className,
}: MenuItemProps) => {
	return (
		<Link href={url}>
			<div
				className={`${
					className ?? ''
				} flex items-center gap-2 hover:bg-black p-2 rounded-md`}
			>
				{icon}
				<span>{text}</span>
			</div>
		</Link>
	)
}

export default MenuItem
